I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 14, in script
    init python:
  File "game/script.rpy", line 14, in script
    init python:
  File "game/script.rpy", line 22, in <module>
    client.connect(ip_port)
ConnectionRefusedError: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\ChatSukonbu\renpy-8.0.3-sdk\renpy\bootstrap.py", line 277, in bootstrap
    renpy.main.main()
  File "C:\ChatSukonbu\renpy-8.0.3-sdk\renpy\main.py", line 558, in main
    renpy.game.context().run(node)
  File "game/script.rpy", line 14, in script
    init python:
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/site-packages/future/utils/__init__.py", line 441, in raise_
  File "game/script.rpy", line 14, in script
    init python:
  File "C:\ChatSukonbu\renpy-8.0.3-sdk\renpy\ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\ChatSukonbu\renpy-8.0.3-sdk\renpy\python.py", line 1061, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 22, in <module>
    client.connect(ip_port)
ConnectionRefusedError: [WinError 10061] 대상 컴퓨터에서 연결을 거부했으므로 연결하지 못했습니다

Windows-10-10.0.22631 AMD64
Ren'Py 8.0.3.22090809
스콘부짱GPT 0.9.0_test
Sat Dec 30 15:51:56 2023
